[package]
name = "polynomials"
version = "0.1.0"
authors = ["fmerg <fmerg@grnet.gr>"]
edition = "2018"

[dependencies]
bls12_381 = "0.4.0"
backend = { path="../backend" }

[dev-dependencies]
util = { path = "../util" }
criterion = "0.3.4"

[[bench]]
name = "univariate"
harness = false
