image: rust:latest

stages:
  - test
  - demo

test:
  # stage: test
  interruptible: true
  script:
    - cargo test --verbose

demo:
  # stage: demo
  interruptible: true
  script:
    - ./demo.sh --release 50 40 30 3 2 
