image: rust:latest

# stages:
#   - test
#   - demo

test:
  # stage: test
  interruptible: true
  script:
    - ./test.sh

demo:
  # stage: demo
  interruptible: true
  script:
    - ./demo.sh --release 50 40 30 3 2 

compile-benches:
  # stage: ...
  interruptible: true
  script:
    - cargo bench --no-run
