image: rust:latest

stages:
  - backend
  - polynomials
  - circuits
  - protocol


test_backend:
  stage: backend
  script:
    - cd backend
    - cargo test --release --verbose

test_polynomials:
  stage: polynomials
  needs: [test_backend]
  script:
    - cd polynomials
    - cargo test --release --verbose

test_circuits:
  stage: circuits
  needs: [test_polynomials]
  script:
    - cd circuits
    - cargo test --release --verbose

test_protocol:
  stage: protocol
  needs: [test_circuits]
  script:
    - cd protocol
    - cargo test --release --verbose
