# [package]
# name = "snarky"
# version = "0.1.0"
# authors = ["fmerg <fmerg@grnet.gr>"]
# edition = "2018"

[workspace]
members = [
    "util",
    "backend",
    "polynomials",
    "circuits",
    "protocol",
]

[profile.release]
# codegen-units = 1
lto = true
# opt-level = 3
