# [package]
# name = "snarky"
# version = "0.1.0"
# authors = ["fmerg <fmerg@grnet.gr>"]
# edition = "2018"

[workspace]
members = [
    "util",
    "backend",
    "polynomials",
    "circuits",
    "protocol",
]

# [profile.release]
# lto = true
# panic = 'abort'
# codegen-units = 1
